# Delete instance Security Groups rules
  - name: Delete Http 80 rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ instance_security_group_name}}"
      start_port: 80
      end_port: 80
      state: absent
    tags: sgr

  - name: Delete Https 443 rule
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ instance_security_group_name}}"
      start_port: 443
      end_port: 443
      state: absent
    tags: sgr

  - name: Delete instance SSH rule for remote access
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ instance_security_group_name}}"
      start_port: 22
      end_port: 22
      state: absent
    tags: sgr
